[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Configura a velocidade do monitor serial do PlatformIO para bater com o seu código
monitor_speed = 115200

; Ativa o USB interno para que o Serial.print funcione perfeitamente na Super Mini
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1