[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino

monitor_speed = 115200

upload_port = /dev/ttyUSB0

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1